### ISSUE TITLE
RGBA Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anders9ustafsson/fjcore#7]
```
the only way to work with this in c# is with a wrapper to c libraries.

Microsoft doesn`t support this.

it would be great if fjcore support this.


```

Original issue reported on code.google.com by `charcost...@gmail.com` on 8 Jul 2009 at 9:46

Attachments:
* [Footman.jpg](https://storage.googleapis.com/google-code-attachments/fjcore/issue-7/comment-0/Footman.jpg)

**Comment by anders9ustafsson** [comment]
This issue was moved to briandonahue/FluxJpeg.Core#13
